version: '3'
services:

   mongodb:
      image: mongo:latest
      restart: on-failure
      volumes:
        - $HOME/data/kaliberDB:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: kaliber
        MONGO_INITDB_ROOT_PASSWORD: Kal1b3r
      ports:
        - 27017:27017
